export class ContacDTO {
  constructor(
    public firstName: string = '',
    public lastName: string = '',
    public emailAddress: string = '',
    public phoneNumber: string = '',
    public address: string = '',
    public reportType: string = '',
    public otherReport: string = '',
    public propertyType: string = '',
    public purposeType: string = '',
    public otherPurpose: string = '',
    public dwellingStyleType: string = '',
    public dwellingType: string = '',
    public otherDwellingType: string = '',
    public additionalInfo: string = '',
    public purchaseType: string = '',
    public constructionCompany: string = '',
    public otherConstructionCompany: string = '',
    public houseModel: string = '',
    public purchasePrice: string = '',
    public mortgageType: string = '',
    public lender: string = '',
    public refinanceAmount: string = '',
    public loanToValue: string = '',
    public relocationType: string = '',
    public otherRelocationType: string = '',
    public referenceNumber: string = '',
    public condoFees: string = '',
    public parking: string = '',
    public parkingType: string = '',
    public parkingSpaces: string = '',
    public locker: string = '',
    public specialAssessments: string = '',
    public isRetrospectiveAppraisal: string = '',
    public retrospectiveAppraisalDate: string = '',
  ) { }
}
